
int bitAnd(int, int);
int test_bitAnd(int, int);
int byteSwap(int, int, int);
int test_byteSwap(int, int, int);
int logicalShift(int, int);
int test_logicalShift(int, int);
int bitParity(int);
int test_bitParity(int);
int logicalNeg(int);
int test_logicalNeg(int);
int tmin();
int test_tmin();
int sign(int);
int test_sign(int);
int divpwr2(int, int);
int test_divpwr2(int, int);
int negate(int);
int test_negate(int);
int isPositive(int);
int test_isPositive(int);
int isLessOrEqual(int, int);
int test_isLessOrEqual(int, int);
int ilog2(int);
int test_ilog2(int);
unsigned float_neg(unsigned);
unsigned test_float_neg(unsigned);
unsigned float_i2f(int);
unsigned test_float_i2f(int);
unsigned float_twice(unsigned);
unsigned test_float_twice(unsigned);
